### ISSUE TITLE
ipsec fails to start

### ISSUE THREAD

**Issue by RMerl** [RMerl/asuswrt-merlin.382#27]
```
admin@RT-AC86U-DFD8:/proc/1# /usr/lib/ipsec/starter 
/usr/lib/ipsec/starter: error while loading shared libraries: libpthread.so.0: cannot open shared object file: No such file or directory
```

This seems to be an environment issue, as setting LD_LIBRARY_PATH to point at /lib/aarch64 before running starter fixes it.

Attempted to add it to /etc/ld.so.conf at build time, same result.

**Comment by RMerl** [comment]
Original ink issue fixed with 7fd5e449547649f2720d0a7199bab2bbea02853b, however a different issue is caused by the mismatch in architecture between OpenSSL (32-bit) and Strongswan (64-bit).

**Comment by RMerl** [comment]
Compiling as a 32-bit version seems to solve that issue, however it seems like Asus hasn't really finished developping this yet, as all the plugins config files are missing from the firmware.

Closing this for now - strongswan implementation doesn't seem to be anywhere close to be complete yet.

**Comment by odkrys** [comment]
as all the plugins config files are missing from the firmware.

It would work if you make symlinks when build firmware. (I don't know how)
ln -s /usr/etc/strongswan.d /etc/strongswan.d
ln -s /usr/etc/ipsec.d /etc/ipsec.d

I could connect to my IPSec server on my android but 64bit kernel and 32bit strongswan made xfrm communication issue, so I got a disconnection signal from server immediately.

I guess IPSec server will work on 32bit kernel (AC88U) with that symlinks.
It's worth a try.

**Comment by RMerl** [comment]
I'll let Asus's engineers finish what they started - no point in wasting my time on something they're already working on.
