### ISSUE TITLE
RC error:"collect2: ld returned 1 exit status

### ISSUE THREAD

**Issue by li7862756** [RMerl/asuswrt-merlin.382#32]
[rc] CC rc
/home/nulee/work/am-toolchains/brcm-arm-hnd/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin/../lib/gcc/arm-buildroot-linux-gnueabi/5.3.0/../../../../arm-buildroot-linux-gnueabi/bin/ld: 找不到 -lbwdpi
collect2: 错误：ld 返回 1
Makefile:578: recipe for target 'rc' failed
make[6]: *** [rc] Error 1
make[6]: Leaving directory '/home/nulee/work/ac86u/release/src/router/rc'

**Comment by azdps** [comment]
Try installing package libws. I had a similar error and installing the libws package solved this problem.
