### ISSUE TITLE
OpenVPN access type improvement.

### ISSUE THREAD

**Issue by odkrys** [RMerl/asuswrt-merlin.382#39]
I saw the commit which added access type options to the GUI by Asus.

https://github.com/RMerl/asuswrt-merlin.382/commit/d293bdd6576de28fef8dc6f4d852bb1ee4541e34

Could you add one more type 'internet only'?

A specific case when I need to open vpn server for my friend who lives in overseas to watch region restricted content in our country but I don't want that he access to my lan.
That option would be great.

**Comment by RMerl** [comment]
That new setting is just a preset, it's not a new feature.

What you ask would require additional code to block LAN access.
