### ISSUE TITLE
[Q] About KRACK

### ISSUE THREAD

**Issue by S0und** [RMerl/asuswrt-merlin.382#41]
https://www.krackattacks.com/

At this point do we have to wait for ASUS to release a fix, or can we expect Merlin to fix the vulnerability?  From my understanding the client is tricked who eventually will connect to the cloned network, so maybe AP side update is not even necessary?

**Comment by RMerl** [comment]
From what little info I have so far (I haven't had time to study the disclosure yet), this only affects STA mode, not AP mode.  Therefore in theory, the only updates needed for the router would be for Repeater/Bridge modes.

There's a chance this might require a newer nas exe from Broadcom, in which case I can't do anything until Asus issues an update.

No idea yet if the firmware-included wpa_supplicant is used in Repeater mode.

**Comment by Ryujinra** [comment]
@RMerl Evidently, there is an AP-side patch to hostapd that can address unpatched clients; see here: https://github.com/RMerl/asuswrt-merlin/issues/1511#issuecomment-337542831

**Comment by RMerl** [comment]
Asuswrt does not use hostpad.

**Comment by Ryujinra** [comment]
Would it still be possible to disable the retransmission of EAPOL-Key frames in wpa_send_eapol() in wpa_auth.c?

**Comment by themiron** [comment]
asuswrt don’t use wpa_supplicant for anything wireless on bcm models. it’s for wired 802.1x there

**Comment by TecumsehSamp** [comment]
Do you know if wpa_supplicant is used in AP mode for wireless clients?

**Comment by RMerl** [comment]
HND platform fixed with commit 71f5b52aadfd51ac93cace52c3f4d3937640e7be.

Still no updated SDK available for SDK7114.

**Comment by RMerl** [comment]
SDK7114 fixes merged with fd20998, which fixes the last remaining models on the 382 branch.
