### ISSUE TITLE
Update minidlna to 1.2.1

### ISSUE THREAD

**Issue by RMerl** [RMerl/asuswrt-merlin.382#45]
Update minidlna to latest version (currently 1.2.1).

**Comment by RMerl** [comment]
Asuswrt's minidlna is too heavily patched at this point, it's too much work merging 1.2.1 on top of it due to the 1.2.1 changes.  This will have to be done upstream by Asus.

**Comment by bchr** [comment]
The latest is now 1.3.0 released 24-Nov-2020 and it fixes two CVE's. I hope they have backported those patches.
On 386.1_2, `minidlna -V` outputs `Version 1.2.1`.
