### ISSUE TITLE
rc/services: small issues of root user shadow setting and tunnelbroker ddns iptables rule

### ISSUE THREAD

**Issue by noblehng** [RMerl/asuswrt-merlin.382#55]
The `/etc/shadow` setting of the `http_user`, a.k.a. root, is set to `%s:%s:0:0:99999:7:0:0:` in [here](https://github.com/RMerl/asuswrt-merlin.382/blob/master/release/src/router/rc/services.c#L702). According to the [man page](https://linux.die.net/man/5/shadow), the last 0 make the account expired, and the first force a password reset. This cause OpenSSH server to deny root user login, it doesn't affect dropbear because dropbear doesn't check those fields. Users can modify /etc/shadow to fix this, but it doesn't seem to have a good hook to do that when changing the `http_user` name or password on the webui.

The tunnelbroker ddns service [insert a rule in iptables](https://github.com/RMerl/asuswrt-merlin.382/blob/master/release/src/router/rc/services.c#L3121) for ping back every time it runs, this cause a lot of duplicate rules. It is better to try to delete the same rule before inserting it again.

**Comment by RMerl** [comment]
Fixed with d0ba7a4 and 0b8d6eb.
