### ISSUE TITLE
Source IP and Destination IP Aliases

### ISSUE THREAD

**Issue by pmagid** [RMerl/asuswrt-merlin.382#63]
In the OpenVPN Client Settings please add a section that allows for the creation of aliases or lists of IPs that refer to lists or blocks of internal or external IPs.  These aliases should then be referable in the Source IP drop down and the Destination IP text box.   For example, currently there is no way to create a rule that sends traffic over the WAN and not the VPN when a grouping of internal devices that require Netflix streaming are accessing the grouping or alias that represents the Netflix IPs.

**Comment by RMerl** [comment]
The lLnux routing database relies on IPs.  Adding such an option would make the management interface way too complicated to use and to implement.

Easiest way to handle this for you would be to regroup the target device in a small subnet, then create a rule for that subnet.  It can be a small /28 for instance which would cover up to 14 clients with one single rule - just assign those specific clients on the DHCP reservation.
